### ISSUE TITLE
./bootstrap/bin/forge variant=shipping install on macOS Sierra I get a failure because of a missing module

### ISSUE THREAD

**Issue by willmbaker** [cwbaker/forge#4]
When I run the command...
```
./bootstrap/bin/forge variant=shipping install
```

I get the following output...

```
~/insertcoin/process/thirdparty/forge> ./bootstrap/bin/forge variant=shipping install
...cess/thirdparty/forge/src/forge/lua/forge/xcode/init.lua:2: module 'forge.cc.clang' not found:
	no field package.preload['forge.cc.clang']
	no file '/Users/willmbaker/insertcoin/process/thirdparty/forge/src/forge/lua/forge/cc/clang.lua'
	no file '/Users/willmbaker/insertcoin/process/thirdparty/forge/src/forge/lua/forge/cc/clang/init.lua'
	no file '/usr/local/lib/lua/5.3/forge/cc/clang.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './forge/cc/clang.so'
	no file '/usr/local/lib/lua/5.3/forge.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './forge.so'
```

I believe the error is because `forge.cc.clang` is missing, but I'm not sure where it looks for those modules. Am I running it from the wrong location?

**Comment by cwbaker** [comment]
Thanks again Will.  I'm unsure why the CI doesn't throw that error?

However should be fixed on the latest *master* revision.  Let me know how it goes.

The problem is that I moved all of those modules up from the *cc* directory to be just within the *forge* directory.  See the [src/forge/lua/forge](https://github.com/cwbaker/forge/tree/master/src/forge/lua/forge) directory for the Lua build scripts.  The last level *forge* directory is the *forge* referred to in the `require()` calls.

Thanks,
Charles

**Comment by willmbaker** [comment]
Great! That works fine now. Thanks for the quick response! ;)
